name: Cypress Tests
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Migrations
      run: |
        python manage.py makemigrations
        python manage.py migrate --run-syncdb
    - name: Run Tests
      run: |
        python manage.py test
    - name: Run Django Server
      run: |
        python manage.py runserver &
    - name: Checkout
      uses: actions/checkout@v2
    - name: Run Cypress Tests
      uses: cypress-io/github-action@v4
      with:
        start: yarn run cypress run
      
    